### ISSUE TITLE
frameworkalternate issues with F# signatures

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#360] opened 2018-10-11 06:45 UTC
I've noticed mdoc doesn't correctly apply the frameworkalternate values to the F# signatures (or split them when they are the same)

See the following PR to see my attempt to fix it manually:
https://github.com/dotnet/dotnet-api-docs/pull/607

Hopefully, won't be undone next time we run CI.

**Comment by joelmartinez** [comment] 2018-10-11 13:34
Yeah this is "by design" ... I'm 100% not suggesting that it's ideal, but as it stands, if there's anything about the member that warrants a separate "FrameworkAlternate", the whole set of signatures will be broken out separately. So to use a specific example from this PR:

So in [this case](https://github.com/dotnet/dotnet-api-docs/blob/63ba692f436984a45035a2a64f626a8c24c84756/xml/Microsoft.VisualBasic/Interaction.xml#L1322), you'll notice that a single parameter is named _slightly_ differently (different case). So because of that, it causes the ILASM signatures to differ (strictly speaking), which kicks off the separation into `FrameworkAlternate`s. Now, in the case of the F# signatures, it doesn't actually matter, because the signature doesn't contain the parameter name ... but that's how it works today for better or worse.

I'm going to close this issue, because it's the same issue as https://github.com/mono/api-doc-tools/issues/346 ... while I agree that it's not as nice, please let me know if there are any actual systemic issues that arise from this. I would definitely like to address it eventually, and if it's a blocker on something that would raise it's priority :)

**Closed by joelmartinez** 2018-10-11 13:34 UTC

**Comment by mairaw** [comment] 2018-10-11 16:49
I forgot about #346 but I can't see how this could be by design. 

Let's look at an example from my PR (and I'm being careful with casing and all for the parameter names):
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.VisualBasic/FileSystem.xml#L383
An F# signature with a parameter called Pathname is applied to netframework-1.1;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8

https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.VisualBasic/FileSystem.xml#L387
An F# signature with a parameter called PathName is applied to netframework-2.0

All the other languages have the proper list of Pathname for 1.1 and PathName for 2.0+.
