### ISSUE TITLE
[mdoc] Support for C++ signatures

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#132] opened 2017-10-12 12:46 UTC
Support API entity signatures in C++ (this includes WinRT C++ and C++/Cx)

**Comment by joelmartinez** [comment] 2017-10-12 13:24
@dend, for the sake of gathering all details for the implementation, where can we find syntax details for both winrt C++, and c++/Cx ? Is there any appreciable difference between the two?

**Comment by katebialiatka** [comment] 2017-10-18 14:13
@dend @joelmartinez 
Af far as I understood we need to support all types - C++/CLI, C++/WinRT and C++/CX. Is it correst?
If so, could you please advice, whether there are any docs about how they can be mapped and what are syntax differences between them. This would be extremely helpful.
Also, do we need three different C++ formatters or there will be one unified?

**Comment by joelmartinez** [comment] 2017-10-18 14:25
I will defer to @dend here, as I'm not very experienced with any of the `c++/*` family of technologies. 

On the last question about the formatters, I will say that if there is any appreciable difference and we have to list them separately, then yes we would need separate formatters. However, I'm guessing that you can probably use inheritance to share much of the functionality since (I assume) the syntax would be similar if they will truly be different.

Additionally, I should mention one more requirement that we probably haven't discussed in these various language/signature items ... the only default signature formatters are ILASM and C#. We have already added `docid`, which can be triggered by passing [`--use-docid`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L198) on the CLI. I would like to generalize this so that we can use a new CLI parameter called `-lang F#`, `-lang C++/CLI`, etc, to add the additional signature formatters. For backwards compatibility, `--use-docid` should still work (probably just call the same function as the new `-lang` parameter with `docid` as the argument).

**Comment by katebialiatka** [comment] 2017-10-18 15:03
@joelmartinez Yes, agree about inheritance. My question was in a bit other direction - whether we'll have several c++ examples depending on the type, on condition syntax differs.

From the first glance, C++/WinRT and C++/CX are like extension to the usual one for work with WinRT. So I assume syntax and purpose of usage might differ.

@dend, could you please comment on this?
Also a question for backward compatibility - do we need to translate C++/WinRT specific features to ILASM and C# if any?

**Comment by dend** [comment] 2017-10-18 18:59
**C++/Cx** documentation:
https://docs.microsoft.com/en-us/cpp/cppcx/visual-c-language-reference-c-cx

**C++/WinRT** documentation:
https://github.com/Microsoft/cppwinrt

cc: @katebialiatka @joelmartinez

**Comment by jonpryor** [comment] 2017-10-19 21:09
> Also a question for backward compatibility - do we need to translate C++/WinRT specific features to ILASM and C# if any

Conceptually, no. The intent of `<MemberSignature/>` is to provide a syntax that is understandable to a developer in that language. If you e.g. have `const` C++ member function which is none-the-less invocable by C#, and C# has no conception of `const` member functions, then there is no need to "translate" this feature into C#.

...with one or two exceptions:

1. IIRC mdoc (in this repo) uses `DocId` for member uniqueness purposes. Rephrased, a question: how does `mdoc` know if a member is being added to the XML? It knows because the member doesn't already exist in the XML. How does it know this? Because `//MemberSignature[@Language='DocId']` is *unique*.

2. Older versions of mdoc don't use DocId for uniqueness purposes, they use the C# member signature for uniqueness purposes.

We *probably* don't need to worry/care about older versions of mdoc.

We *do* need to care about `DocId`. Returning to the C++ example, if you overload a member function, one `const`, one non-`const`, and they both result in the same `DocId` value, There Will Be Problems™.

*Additionally*, the `DocId` value is the value used in `//see/@cref`, so if e.g. `const` and non-`const` overloads result in the same DocId, value, you won't be able to link to to the desired overload either!

**Comment by joelmartinez** [comment] 2017-10-19 21:14
@jonpryor actually, it's using the ILASM signature for uniqueness as of a recent release :) However, your point about `//see/@cref` is certainly duly noted. We're currently dealing with an issue that showed up with .net 4.7.1, where a type in `System.Printing` has some overloads of `op_Implicit` that differ only via a `modreq`. As these are present in the ILASM, they show up as different `Member` nodes ... but it confounds various other parts of the pipeline.

**Comment by katebialiatka** [comment] 2017-11-02 15:53
@joelmartinez Currently I'm testing C++ formatter and there is several questions which needs to be addressed.  Could you please take a look?
I've used C++/CLI as a basement since it looked impossible to convert managed signatures to unmanaged code. In addition, majority of C++ examples in MSDN/Docs use managed version.

1. There is no support for extenson methods. However, there are several workarounds how to achieve similar results. The question is what should be generated in xml for extension methods? See options below:

-  Use regular static methods instead (by the way, extensions written in C# are called as static methods in c++)
 https://stackoverflow.com/questions/5643734/how-to-use-linq-in-c-cli-in-vs-2010-net-4-0/5645267#5645267
 

- Mark method and class-container with the ExtensionAttribute (Namespace: System.Runtime.CompilerServices; Assembly:  mscorlib (in mscorlib.dll)). 
According to the documentation, it should solve the problem. However, for me this does not work - I'm not able to compile such code as attribute is not visible somehow.
 https://stackoverflow.com/questions/6012578/how-can-i-create-net-extension-methods-by-c-cli

-  Add text like "Not Supported"

2. There is no internal access modifier in C++. But there is analog for protected internal -> public protected. Hovewer this does not compile for me. Can you possibly suggest how this need to be applied?
 http://weblogs.thinktecture.com/cnagel/2004/12/access-modifiers-ccli-vs-c-vs-vb.html

3. There is no 'unsafe' keyword in the C++ but there is concept of pointers. Do we need to identify somehow in the documentation that class was marked as 'unsafe'?
In addition, C# formatter does not add 'unsafe' keyword in documentation. 
Example:
`public unsafe class Widget : IProcess `
`<TypeSignature Language="C#" Value="public class Widget : Mono.DocTest.IProcess" />`
Is it a bug or expected behaviour? 

4. struct in c++ is unmanaged object. Because of this it cannot be used together with managed objects. So there is two options how to overcome this: use 'value class' or mark struct as reference type ('ref struct'). Which option is more appropriate to use during class declaration?
 Example:
` public struct DocValueType : IProcess`
`public value class Mono::DocTest::DocValueType : Mono::DocTest::IProcess`
`public ref struct Mono::DocTest::DocValueType : Mono::DocTest::IProcess`
 P.S. For generic type constraint it is suggested to use value class. So question remains only for class declaration and return types.

5.  There is no possibility for default parameters. The workaround for this is to add attributes `'DefaultParameterValue'` and` 'Optional'.` However, it is stated that with adding those attributes code can behave unpredictably. In addition, I have troubles with compiling such type of code.
https://stackoverflow.com/questions/4974237/optional-parameters-in-managed-c-cli-methods/4974528#4974528
What would be the desired behaviour in this case? How to reflect optional parameters in documentation?

**Comment by joelmartinez** [comment] 2017-11-03 20:29
1. I would definitely go for the second approach ... remember, the ideal approach for mdoc formatters, is to represent *the definition* of a type or member (with the [exception of F#](https://github.com/mono/api-doc-tools/issues/108#issuecomment-341772570), since it's a functional language, and that community has certain expectations/standards for this stuff). So when we encounter a static method that has `this` on the first parameter (ie. an extension method), the C++ signature would represent how to define that if you were writing this method in C++. 
    - So with that said, you said you can't seem to get that to compile ... I would keep trying, and maybe see if you can look up documentation on why you can't get it to compile. 
    - worst case, if you can't get it to compile and it truly is not possible to define an extension method that can be consumed as such when referenced by a C# library, then the formatter should say that it's not supported (in the formal sense, that it doesn't even write out a signature XML node).
2. As above, if you cannot express something in c++ that can then be consumed by a C#/F# library, then the formatter should return `false` on `IsSupported`. However, an internal type/member wouldn't be documented in mdoc anyways, right? so you may not really have to do much work here.
3. This is actually expected behavior (for now, at least). in C#, there is no metadata written to the type/method definition that indicates that a method contains unsafe code ... it's more of a language-specific thing that doesn't actually get written to the assembly. _note_, there are apparently some ways that one could figure it out, if you look at the actual method body IL ... but that's (currently) out of scope.
4. Remember that a .NET `struct` actually inherits (implicitly) from [`System.ValueType`](https://docs.microsoft.com/en-us/dotnet/api/system.valuetype?view=netframework-4.7.1). Aside from that, I would do a test with the types that you're defining and testing with ... when you instantiate it, can you call the `.GetType()` method, and then subsequently [`Type.IsValueType`](https://docs.microsoft.com/en-us/dotnet/api/system.type.isvaluetype?view=netframework-4.7.1#System_Type_IsValueType). If the runtime returns `true`, then you know you've defined it correctly as a value type.
5. Oof, that's a tough one ... it would seem that this is not _really_ a supported language feature. Remember that the idea is that you should be able to define it in C++, and consume it from another .net language. So, if you can't make a value type that C# would understand as a value type (ie. boxing it when assigning it to `object`), then the formatter should say it's not supported.

**Closed** 2018-01-11 22:11 UTC
Labels: enhancement
