### ISSUE TITLE
mdoc 5.5 fails to reflect UWP Community Toolkit documentation

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#208] opened 2018-02-20 20:54 UTC
Binaries attached:
[uwp.zip](https://github.com/mono/api-doc-tools/files/1741821/uwp.zip)

This is also dependent on UWP assemblies, referenced in my script via:

```
 -L "C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0"
```

Error:

```
2018-02-20T20:50:39.4288283Z Member Added: public void StopEnumeration ();
2018-02-20T20:50:39.4444551Z Member Added: public static Microsoft.Toolkit.Uwp.Connectivity.BluetoothLEHelper Context { get; }
2018-02-20T20:50:39.4444551Z Member Added: public static bool IsBluetoothLESupported { get; }
2018-02-20T20:50:39.5381822Z ##[error]mdoc: System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Documentation.Updater.Formatters.CppFormatters.CppFullMemberFormatter.AppendTypeName(StringBuilder buf, TypeReference type, DynamicParserContext context)
   at Mono.Documentation.Updater.Formatters.CppFormatters.CppFullMemberFormatter.AppendGenericType(StringBuilder buf, TypeReference type, DynamicParserContext context, Boolean appendGeneric)
   at Mono.Documentation.Updater.MemberFormatter._AppendTypeName(StringBuilder buf, TypeReference type, DynamicParserContext context, Boolean appendGeneric)
   at Mono.Documentation.Updater.MemberFormatter.GetTypeName(TypeReference type, DynamicParserContext context, Boolean appendGeneric)
   at Mono.Documentation.Updater.Formatters.CppFormatters.CppFullMemberFormatter.GetTypeNameWithOptions(TypeReference type, Boolean appendHat, Boolean appendGeneric)
   at Mono.Documentation.Updater.Formatters.CppFormatters.CppFullMemberFormatter.GetPropertyDeclaration(PropertyDefinition property)
   at Mono.Documentation.Updater.MemberFormatter.GetDeclaration(IMemberDefinition member)
   at Mono.Documentation.Updater.MemberFormatter.GetDeclaration(MemberReference mreference)
   at Mono.Documentation.MDocUpdater.UpdateSignature(MemberFormatter formatter, MemberReference member, XmlElement xmlElement)
   at Mono.Documentation.MDocUpdater.UpdateMember(DocsNodeInfo info, FrameworkTypeEntry typeEntry, Dictionary`2 implementedMembers)
   at Mono.Documentation.MDocUpdater.MakeMember(XmlDocument doc, DocsNodeInfo info, XmlNode members, FrameworkTypeEntry typeEntry, Dictionary`2 iplementedMembers)
   at Mono.Documentation.MDocUpdater.DoUpdateType2(String message, XmlDocument basefile, TypeDefinition type, FrameworkTypeEntry typeEntry, String output, Boolean insertSince)
   at Mono.Documentation.MDocUpdater.StubType(TypeDefinition type, String output, IEnumerable`1 importers, String Id, String Version)
   at Mono.Documentation.MDocUpdater.DoUpdateType(TypeDefinition type, FrameworkTypeEntry typeEntry, String basepath, String dest)
   at Mono.Documentation.MDocUpdater.DoUpdateAssembly(AssemblySet assemblySet, AssemblyDefinition assembly, XmlElement index_types, String source, String dest, HashSet`1 goodfiles)
   at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
   at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
   at Mono.Documentation.MDoc.Run(String[] args)
   at Mono.Documentation.MDoc.Main(String[] args)
See `mdoc help' for more information or use --debug to diagnose.
```

**Comment by dend** [comment] 2018-02-21 23:44
This same issue is also applicable to PSCore binaries:

[pscore-bin.zip](https://github.com/mono/api-doc-tools/files/1746115/pscore-bin.zip)

CI script triggers via:

```
& ($Env:BUILD_REPOSITORY_LOCALPATH + "\_bin\mdoc.exe") update -fx ($Env:BUILD_REPOSITORY_LOCALPATH + "\_all") -o  ($Env:BUILD_REPOSITORY_LOCALPATH + "\_all-out") --debug -lang docid -lang c++/cli -lang c++/cx -lang c++/winrt -lang vb.net -lang fsharp --delete -L "C:\Program Files (x86)\Windows Kits\10\References\10.0.15063.0"
```

**Comment by joelmartinez** [comment] 2018-02-26 21:25
Ok ... so I'm working on reproducing this, but it looks like the package is omitting a dependency, because I'm getting:

```
Failed to resolved assembly: 'Microsoft.Graphics.Canvas'
```

Looks like it hits this error when documenting [`LoadTimeEffectHandler`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.ui.animations.loadtimeeffecthandler?view=uwp-toolkit-ui-animations-2.0.0), which takes a parameter of [`CanvasBitmap`](https://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasBitmap.htm).

I'm going to try now with the pscore assemblies to see if I can reproduce this error with that set

**Comment by joelmartinez** [comment] 2018-02-26 22:16
@dend ok, I've been able to reproduce and resolve this issue. I'm experiencing #209 with the provided PSCore assemblies, so I'm going to work on that now ... however, I can work on making sure the other runs successfully as well if you can resolve the `Microsoft.Graphics.Canvas` dependency.

**Comment by joelmartinez** [comment] 2018-02-28 20:30
This is resolved with https://github.com/mono/api-doc-tools/releases/tag/mdoc-5.5.0.1

**Closed** 2018-02-28 20:30 UTC
