### ISSUE TITLE
mdocs does not always ignore dependencies

### ISSUE THREAD

**Issue by mattleibow** [mono/api-doc-tools#2] opened 2016-10-19 14:52 UTC
When using MCS directly, mdoc ignores dependencies:  
https://github.com/joelmartinez/monodoc-renderer-sample

    make  SampleCodeDocs

When using MSBUILD, mdoc throws:  
https://github.com/mattleibow/MdocTestLib

    make update

**Comment by mattleibow** [comment] 2016-10-19 14:55
My Exception:

```
mdoc update --debug MdocTestLib/bin/Debug/MdocTestLib.dll -o MdocTestLibDocs
mdoc: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x00121] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) [0x00007] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.DefaultAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) [0x0002b] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.MetadataResolver.Resolve (Mono.Cecil.TypeReference type) [0x00040] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.ModuleDefinition.Resolve (Mono.Cecil.TypeReference type) [0x00006] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.TypeReference.Resolve () [0x00013] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.Mixin.CheckedResolve (Mono.Cecil.TypeReference self) [0x00000] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum (Mono.Cecil.TypeReference enum_type) [0x00000] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue (Mono.Cecil.TypeReference type) [0x0003d] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.SignatureReader.ReadCustomAttributeElement (Mono.Cecil.TypeReference type) [0x00032] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.SignatureReader.ReadCustomAttributeFixedArgument (Mono.Cecil.TypeReference type) [0x00018] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments (Mono.Cecil.CustomAttribute attribute, Mono.Collections.Generic.Collection`1[T] parameters) [0x00034] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature (Mono.Cecil.CustomAttribute attribute) [0x00045] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.CustomAttribute.<Resolve>m__1 (Mono.Cecil.CustomAttribute attribute, Mono.Cecil.MetadataReader reader) [0x00000] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.ModuleDefinition.Read[TItem,TRet] (TItem item, System.Func`3[T1,T2,TResult] read) [0x00018] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.CustomAttribute.Resolve () [0x0001d] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Cecil.CustomAttribute.get_ConstructorArguments () [0x00000] in <364321ccd6674266bec9cd4fab3f2d34>:0 
  at Mono.Documentation.MDocUpdater+<GetCustomAttributes>c__Iterator0.MoveNext () [0x0013b] in <d92e86130af3471690177d2a00336053>:0 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <63992662b765477a898ef49cdcc99ee2>:0 
  at Mono.Documentation.MDocUpdater.MakeAttributes (System.Xml.XmlElement root, System.Collections.Generic.IEnumerable`1[T] attributes, Mono.Cecil.TypeReference t) [0x00000] in <d92e86130af3471690177d2a00336053>:0 
  at Mono.Documentation.MDocUpdater.AddIndexAssembly (Mono.Cecil.AssemblyDefinition assembly, System.Xml.XmlElement parent) [0x00162] in <d92e86130af3471690177d2a00336053>:0 
  at Mono.Documentation.MDocUpdater.DoUpdateAssemblies (System.String source, System.String dest) [0x0011b] in <d92e86130af3471690177d2a00336053>:0 
  at Mono.Documentation.MDocUpdater.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x00421] in <d92e86130af3471690177d2a00336053>:0 
  at Mono.Documentation.MDoc.Run (System.String[] args) [0x001f6] in <d92e86130af3471690177d2a00336053>:0 
  at Mono.Documentation.MDoc.Main (System.String[] args) [0x00006] in <d92e86130af3471690177d2a00336053>:0 
See `mdoc help' for more information or use --debug to diagnose.
make: *** [update] Error 1
```

**Comment by mattleibow** [comment] 2016-10-19 15:02
Just a note: this happens with most assemblies, such as Mono.Android or UWP winmd's

**Comment by joelmartinez** [comment] 2016-10-19 15:06
As discussed ... given that this error is originating in mono.cecil, I will update it to use the latest version.

**Comment by joelmartinez** [comment] 2016-10-19 20:57
@mattleibow hmm ... ok, so I've got a new build of mdoc in a branch (see branch [mdoc-cecil-update](https://github.com/mono/api-doc-tools/tree/mdoc-cecil-update)) ... and unfortunately it still gets the same error with the latest version of Mono.Cecil. So the issue is something more pernicious.

@jonpryor ... I wonder if perhaps you could weigh in on the originally reported error. When a library is built with msbuild, it seems to throw off referenced assembly resolution. I've reproduced the error with @mattleibow's [test case](https://github.com/mattleibow/MdocTestLib), and also verified that everything works fine if you use `mcs` in another test case (https://github.com/joelmartinez/monodoc-renderer-sample/commit/a86701345c4cdbe47c17e5830dde93a6847789fe).

Any thoughts would be appreciated ... otherwise, I'll keep investigating :)

**Comment by jonpryor** [comment] 2016-10-19 21:04
```
mdoc: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

That's to be expected, for better or worse, as `mdoc` needs to resolve *all* types, and thus all assemblies, in order to determine method override information (among other things?).

This means that you need to use `mdoc update -L`:

    mdoc update -L path/to/directory/containing/System.Runtime.dll ...

Perhaps we should automatically add some directories to resolve `System.Runtime.dll`, though I'm not entirely convinced that that would be a good idea.

**Comment by joelmartinez** [comment] 2016-10-19 21:08
@jonpryor I don't understand then, in my example I made a .dll, and then did not include that in the `mdoc update`, and it completed successfully. How was that able to complete if it needs every reference explicitly listed ?

**Comment by mattleibow** [comment] 2016-10-19 21:26
@jonpryor As a "side" question... why does it need to resolve all the types? Maybe for inheritance, but on parameter types, can't it just read from the compiled data?

**Comment by jonpryor** [comment] 2016-10-20 12:08
@joelmartinez asked:

> How was that able to complete if it needs every reference explicitly listed ?

I earlier said:

> Perhaps we should automatically add some directories to resolve `System.Runtime.dll`

`mdoc update` uses [`Mono.Cecil.DefaultAssemblyResolver`](https://github.com/mono/cecil/blob/1b5ce06/Mono.Cecil/DefaultAssemblyResolver.cs) which in turn [has code to find an "appropriate" `mscorlib.dll`](https://github.com/mono/cecil/blob/5ee6537/Mono.Cecil/BaseAssemblyResolver.cs#L187-L236), i.e. Cecil has automatic support to search for some directories.

The problem here is twofold:

1. Cecil only special-cases `mscorlib.dll`, *not* `System.Runtime.dll`
2. Assuming that Cecil even *should* special-case more assemblies, (a) what assemblies should it special-case, and (b) where should it look for them?

(2.b) is what makes me question the "sanity" of adding additional "magical search path" logic, in part because of [you don't always want to use the default search path](https://github.com/mono/mono/commit/4e45904553c949f353926f26ddbb444102da9d87).

I am thus torn between the "make it work by default" vs. "make it work *correctly*" aspects, as having it "work by default" against the *wrong* set of assemblies can make one very confused later. (Which is what I went through with the above mono commit: the "original" Xamarin.Android reference XML was inadvertently using the *desktop* `mscorlib.dll`, so when I fixed it to use the *correct* Xamarin.Android `mscorlib.dll`, *lots* of API "breakage" was reported.)

**Comment by jonpryor** [comment] 2016-10-20 12:17
@mattleibow asked:

> As a "side" question... why does it need to resolve all the types?

The "short" (for me!) answer is "search the [`monodocer.cs` source](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs) for all instances of `.Resolve()`," which has 13 matches:

* [Don't report explicit interface method implementations for non-public interfaces](https://github.com/mono/api-doc-tools/blob/e3220b6/mdoc/Mono.Documentation/monodocer.cs#L1276)
* [Don't generate *values* for "public" `const` fields if the field type can't be resolved](https://github.com/mono/api-doc-tools/blob/e3220b6/mdoc/Mono.Documentation/monodocer.cs#L2066)
* [Something something generic method constraints?](https://github.com/mono/api-doc-tools/blob/e3220b6/mdoc/Mono.Documentation/monodocer.cs#L2677)
* [Detecting implemented interfaces](https://github.com/mono/api-doc-tools/blob/e3220b6/mdoc/Mono.Documentation/monodocer.cs#L3241-L3245)
* ...

Then there's [`exceptions.cs`](https://github.com/mono/api-doc-tools/blob/e3220b6/mdoc/Mono.Documentation/exceptions.cs) which needs to determine the type hierarchy to determine whether a possibly thrown exception is caught, and determining the hierarchy requires resolve the types, and thus the assemblies that contain those types.

**Comment by joelmartinez** [comment] 2016-10-20 14:23
@jonpryor Wow, thank you for the incredibly detailed background ... I think I'm starting to understand.

@mattleibow ... so I made an iOS library as a test, the trick was that this error was only triggered in my test case when I made the class inherit from `UIView`, rather than simply having a reference to a type in `Xamarin.iOS.dll` as a method argument or return type. 

I compiled it with:

    mcs AniOSLibrary/AniOSLibrary/MyClass.cs -target:library -r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll

And then added *the directory that contained `Xamarin.iOS.dll`* using the `-L` parameter.

    mdoc update --debug AniOSLibrary/AniOSLibrary/MyClass.dll -o MdocTestLibDocsios -L /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/

Once I did that, it was able to resolve the type/assembly and complete successfully. So you're going to have to add the directory that contains `System.Runtime.dll`, along with any other types it has trouble resolving.

For now, I'm going to close this issue ... but please feel free to keep commenting if you have additional questions or comments :) Thanks for bringing up this issue @mattleibow, and thanks for the insight @jonpryor !

**Closed by joelmartinez** 2016-10-20 14:23 UTC
Labels: bug
