### ISSUE TITLE
Improve the content comparer for imports

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#180] opened 2017-12-08 20:59 UTC
In some cases, the content in imports has barely changed, with potential misplaced additions like spaces or invisible characters added by third-party editors. When those are imported into ECMAXML, there are cases where those are treated as completely new entities, when in reality they are not.

Would be worth investigating ways to minimally normalize the string or compare to the produced ECMAXML-ready output to see whether entities are really the same.

**Comment by mpMelnikov** [comment] 2018-05-11 15:43
Hi @dend !

I'm trying to reproduce the issue. 
1. I run `update -o doctestresult DocTest-v1.dll` and generate the following XML:
```xml
    <Member MemberName="AnotherGreen">
    <!-- .... -->
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
```
2. I add "Some useful description of AnotherGreen." and a space symbol to the `MemberName` value
```xml
    <Member MemberName="AnotherGreen ">     <!--sic! there is an extra space symbol-->
    <!--.....-->
      <Docs>
        <summary>Some useful description of AnotherGreen.</summary>
      </Docs>
    </Member>
```

3. I run `update -o doctestresult DocTest-v1.dll` again, the xml is overwritten:
```xml
    <Member MemberName="AnotherGreen">
    <!--.....-->
      <Docs>
        <summary>To be added.</summary>
      </Docs>
    </Member>
```
Is it the case you have described?

cc: @joelmartinez

**Comment by dend** [comment] 2018-05-12 02:10
This is interesting - maybe the issue was resolved on its own somehow through the many other bug fixes that happened since? 

@joelmartinez - unless you have an example (I should have included one at the time), I am voting to close this.

**Comment by joelmartinez** [comment] 2018-05-12 17:14
ugh ... my apologies, it seems that I must have forgotten to press the "Comment" button on the response I typed out :) 

I think the original issue is being slightly mis-interpreted here. From what I remember, the issue involves importing docxml (you can see an integration test that does this [here](https://github.com/mono/api-doc-tools/blob/master/mdoc/Makefile#L414)).  When content gets imported from triple slash, it gets deposited into the EcmaXML. On a subsequent run, if the content has changed, the way that we're comparing the xml nodes in the importer, to decide whether to copy it from the docxml to the ecmaxml, is basically checking to see if it is exactly the same.

So this sets up a situation where if either the source, or target XML has changed slightly (for example, if someone contributes a change to the EcmaXML for some reason) ... it won't match, and will re-import the docxml, thus duplicating content.

Now, the *bad* thing about this ... is that I'm not sure that I have a good answer for how to solve this. A few thoughts/ideas:

- Should we even be allowing docsets that are importing from docxml (and thus, have the documentation in the source code), to submit edits to the EcmaXML (this is more a @dend question)?
- Instead of copying nodes by comparing the XML content, should we copy it by "index"? that way, it would always re-import the same content node over itself (and overwriting any changes made to ecmaXML ... since the 'truth' is in the source code)?
- Should imported nodes have some sort of attribute that imply they were copied from another source? as long as that attribute is present, we can overwrite it, but if someone contributes content (which would thusly lack this attribute) we would make sure to preserve it?

As you can see, this isn't exactly a simple matter ... it just depends on how we want to proceed. I'm of the opinion that if we're importing from tripleslash docs, that we should treat that as the source of truth and not allow edits (both by policy/ux, and by overwriting from the tripleslash).

**Comment by mpMelnikov** [comment] 2018-05-14 08:28
>Should imported nodes have some sort of attribute that imply they were copied from another source? 

It seems we can control whether the node in EcmaXML should be overwritten by docxml or not by the `overwrite` attribute (#143).

**Comment by dend** [comment] 2018-06-18 18:52
@joelmartinez @mpMelnikov to clarify on the editing experience, if we import from doc XML, we should not let others edit the content, unless that specific content is tagged with `overwrite`, that way avoiding the issue altogether.

**Comment by joelmartinez** [comment] 2018-06-18 19:04
ok, so then @mpMelnikov let's move forward with the index-based approach. So to be clear, it means that only the top level elements of any given entity (ie. so the content in `remarks`, the content in `summary` etc etc should be imported by index. So for example if the `remarks` tag has 5 `para` nodes, then you should replace the 1st one over the 1st one, the 2nd one over the 2nd one and so on. If someone has manually inserted a 6th node in the EcmaXML, then logic dictates that this should remain undisturbed.

It would be curious to know whether it's faster to simply always replace the node no matter what (unless the `overwrite="false"` attribute is present, of course) ... or whether it makes sense to compare the `OuterXml` properties as it does today.

**Comment by mpMelnikov** [comment] 2018-06-19 15:46
@joelmartinez, the logic of MsxdocDocumentationImporter is a little bit complicated, so let's trace how it works now.
In the test, we import the file `DocTest.xml`. In the file we have such a fragment:
```xml
    <members>
        <member name="T:NoNamespace">
             <summary>Namespace Test: [<see cref="N:Mono.DocTest" />] <see href="http://www.mono-project.com/">Mono Project</see></summary>
             <remarks><c>T:NoNamespace</c></remarks>
            </member>
```

In the file `NoNamespace.xml` we have such lines beforehand:
```xml
  <Docs>
    <summary>Namespace Test: [<see cref="N:Mono.DocTest" />] <see href="http://www.mono-project.com/">Mono Project</see></summary>
    <remarks>
```

The importer `MsxdocDocumentationImporter`:
1. Removes `summary` here:
```csharp
if (elem.SelectSingleNode("summary") != null && DocUtils.NeedsOverwrite(e["summary"]))
    MDocUpdater.ClearElement(e, "summary");
```
2. Copies nodes from `DocTest.xml` to `NoNamespace.xml` here:
```csharp
if (!targetNodes.Any (n => sourceXml.Equals (n.Xml) || n.Overwrite?.Value == "false"))
{
    MDocUpdater.CopyNode(child, e);
}
```

In the test, the only case, when the comparison of `OuterXml` happens, is `<extra>` XML node:
```
<extra>Some extra tag value</extra>
```

As you can see, the way it works is somewhere between "always replace the node" and "OuterXml comparison". Should it work the same way for `summary`, `remarks`, `extra`? Does it make sense to iterate through child nodes of `remarks` and `summary` if they are completely overwritten every time?

**Comment by joelmartinez** [comment] 2018-06-19 15:57
@mpMelnikov interesting ... no, you're right, when I briefly looked at the code earlier, I didn't make the distinction between the different node types. Well, I'll only say one thing ... the way it is now, we should be explicit in the guidance for devs/writers, that they have to apply the `overwrite="false"` at the top level node, because adding it to a subnode will not trigger this logic.

Given that, as [@dend suggested earlier](https://github.com/mono/api-doc-tools/issues/180#issuecomment-388522989) I'm going to close this issue until/unless it re-surfaces again :) 

Thanks @mpMelnikov for doing the due diligence here.

**Closed by joelmartinez** 2018-06-19 15:57 UTC
Labels: enhancement
