### ISSUE TITLE
[mdoc] Delta between DocID in FrameworksIndex and type XML

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#51] opened 2017-03-27 17:54 UTC
A good example here would be `System.Dynamic.ExpandoObject`, for which we have the `Add` member.

In the type XML, we have:

```
M:System.Dynamic.ExpandoObject.System#Collections#Generic#ICollection&lt;System#Collections#Generic#KeyValuePair&lt;string,object&gt;&gt;#Add(System.Collections.Generic.KeyValuePair{System.String,System.Object})
```

In `FrameworksIndex` we have:

```
M:System.Dynamic.ExpandoObject.System#Collections#Generic#ICollection&lt;System#Collections#Generic#KeyValuePair&lt;System#String,System#Object&gt;&gt;#Add(System.Collections.Generic.KeyValuePair{System.String,System.Object})
```

The subtle difference here is in how parameter types are resolved - short-aliased vs. FQNs:

```
#Generic#KeyValuePair&lt;string,object
#Generic#KeyValuePair&lt;System#String,System#Object
```

In both cases, it should resolve to a FQN.

**Comment by joelmartinez** [comment] 2017-03-28 12:51
I've been unable to reproduce this so far, and a subsequent run with the latest build seems to have "resolved" the issue. I will close this issue if it doesn't resurface again :)

**Comment by joelmartinez** [comment] 2017-03-29 15:36
@dend ... closing this. Please let me know if the issue resurfaces

**Comment by joelmartinez** [comment] 2017-03-31 14:44
Ok ... so I finally tracked down the root cause of this issue. Turns out that some specific versions of `System.Core` (v2.0.5.0 to be precise) actually report `string,object` as the method name (for example `System.Collections.Generic.IDictionary<string,object>.get_Keys` ... many instances, not just the one referenced above), when cecil is reading the assembly image to build the `MethodDefinition` representation. The other versions of `System.Core` report `System.String,System.Object`, as the other versions of `System.Core.dll` report. 

Before we started using the docid from `DocCommentId`, this type of thing was never a problem because our il and C# signature formatters use the C# type aliases anyways.

It seems that this may just be the way that Mono writes the metadata? I created a small test, using the following class:

```csharp
interface Thing<T,K>
{
	void Add(KeyValuePair<T, K> thing);
}
class MyClass : Thing<System.String, System.Object>
{
	void Thing<System.String, System.Object>.Add(KeyValuePair<System.String, System.Object> thing) { }
}
```
When compiled in VSMac ... cecil reports the method `.Name` as `cecilcoretest.Thing<string,object>.Add`

@jonpryor ... wanted to get your opinion. Is this:

- a "problem" with mono?
- something that cecil should work around for consistency's sake?
- or a scenario that mdoc should work around with some string manipulation?

**Comment by jonpryor** [comment] 2017-03-31 15:43
> Turns out that some specific versions of `System.Core` (v2.0.5.0 to be precise) ...

What makes you say that?

I think it's worse/different: I think it's a difference among compilers. If I take [your code](https://github.com/mono/api-doc-tools/issues/51#issuecomment-290731863) and compile with both Roslyn and mcs:

    $ csc /t:library adt-51.cs /out:adt-csc.dll
    $ mcs /t:library adt-51.cs /out:adt-mcs.dll

Perhaps unsurprisingly, they differ!

**CSC**:

```
$ monodis adt-csc.dll | grep 'Thing<'
           instance default void 'Thing<System.String,System.Object>.Add' (valuetype [mscorlib]System.Collections.Generic.KeyValuePair`2<string, object> thing)  cil managed 
    } // end of method MyClass::Thing<System.String,System.Object>.Add
```

**mcs**:

```
$ monodis *-mcs.dll | grep 'Thing<'
           instance default void 'Thing<string,object>.Add' (valuetype [mscorlib]System.Collections.Generic.KeyValuePair`2<string, object> thing)  cil managed 
    } // end of method MyClass::Thing<string,object>.Add
```

I fail to see how `System.Core` is involved here. The compilers *are* involved, and they're emitting different metadata here. Thus, I think this is a *compiler* difference; Cecil is just returning the values which the compiler emits (as it should!).

**Comment by joelmartinez** [comment] 2017-03-31 15:46
@jonpryor ahh, well, yes ... `System.Core` just happened to be the assembly that triggered the discovery of this. So in that sense, it's not exactly relevant as the root cause of anything :)

Right, so then the question is ... should the compiler change (doubtful, at this point), or should mdoc work around it?

The crux of the problem is that these are the same types being compiled ... so mdoc should treat them as such, even if the compiler implementations are different right?

**Comment by dend** [comment] 2017-03-31 15:46
@joelmartinez @jonpryor I will also add @terrajobst to the conversation. 

Here is the context that we are coming from.

For docs.microsoft.com API ingestion system, we treat DocIDs are the absolute source of truth for referencing objects. The DocID is always consistent across the board, so when we get, say, a `System.String.Concat("blah", "blah")`, the expectation is to receive a `T:System.String.Concat(System.String,System.String)` and we treat `T:System.String.Concat(string,string)` as a different entity.

**Comment by jonpryor** [comment] 2017-03-31 15:47
@joelmartinez asks:

> a "problem" with mono in the way that it writes metadata?

I think it's a "problem" with `mcs`, not mono per-se, in that *presumably* mcs.exe on Windows would produce the same results. Similarly, csc.exe on Mono emits `System.String`, not `string`.

> something that cecil should work around when reading an assembly, for consistency's sake?

No. Cecil should provide *exactly* what's in the assembly. The problem we're running into here is that the assembly contents are compiler-dependent.

> or a scenario that mdoc should work around with some string manipulation?

I fear that this is the only sane solution. We would be, in effect, "working around" an `mcs` "bug"/"feature", and the quotes are necessary because I *doubt* that the behavior here is at all specified in the ECMA standard, so `mcs`' behavior is not "wrong."

**Comment by joelmartinez** [comment] 2017-03-31 15:50
> I fear that this is the only sane solution.
Ok, this is what I too was thinking ... but definitely wanted to get a second opinion. So I will start thinking about how we can reasonably and reliably work around this issue in mdoc.

In the meantime, @jonpryor, do you think it's worth opening an issue on mono's bugzilla about this ... as I imagine consistency would be preferable going forward (even if we have code to work around it for now)?

**Comment by jonpryor** [comment] 2017-03-31 15:52
@dend: Just to clarify, in "normal" use we would generate/receive `T:System.String.Concatenate(System.String,System.String)`.

The problem specifically witnessed here is when dealing with explicit interface implementations: `mdoc` had been assuming that the explicit interface method implementation name could be used as-is, which runs into compiler-specific behavior.

That's Bad™.

Additionally, It's Wrong™: I'd swear I saw an issue here -- but maybe I'm wrong/mistaken -- that VB.NET allows explicit interface method implementations with a user-provided name, which *might not match* what `mdoc` expects *at all*.

Thus, I think `mdoc` needs to alter it's behavior around explicit interface method implementations, and *ignore* what the IL contains, and instead *construct* it based on available information: it knows the interface + interface method being implemented, and (hopefully) can determine the type parameters involved as part of that implementation. Based on that information, it can generate a *canonical* DocumentationID for the member, *ignoring* what the IL provides in this case.

**Comment by joelmartinez** [comment] 2017-03-31 15:56
@jonpryor The VB issue you're referring to is [this one](https://github.com/mono/api-doc-tools/pull/47) ... I ended up working around the problem based on naming conventions (which cleared the short term block).

**Comment by dend** [comment] 2017-05-17 00:50
Just to confirm, @joelmartinez - will @jonpryor 's approach be applied here?

**Comment by terrajobst** [comment] 2017-06-13 16:39
I wouldn't say it's a problem with the compilers; technically explicitly interface implementations are private methods, so the name is arbitrary and the compiler could choose any name. What matters is that the type's vtable is guaranteed to have a mapping for that interface method; there simply isn't a public API that can be called without going through interface dispatch.

The fact that our documentation tools use the private methods as the thing to hang of the docs for explicitly implemented interface methods is a design choice of our tools. We could, in principle, not use the name in metadata but have mdoc generate a unique DocID that is the same regardless of the compile that was used.

However, practically it might be easier to change mcs to emit the names the same way as csc.

**Closed** 2020-03-15 05:35 UTC
Labels: bug
