### ISSUE TITLE
Expected mdoc to not reformat xml but actually reformats the xml

### ISSUE THREAD

**Issue by kingces95** [mono/api-doc-tools#40] opened 2017-03-14 15:42 UTC
After a doc writer adds copy he may reformat the whitespace of the xml and I expect mdoc to preserve that whitespace formatting the next time it's run. What actually happens is mdoc re-formats the white space. See PR https://github.com/xamarin/Xamarin.Forms/pull/813.

One may wonder, "What's the big deal? Just have the doc writer re-run mdoc after his edits to ensure it's been reformatted". The problem is that in order to re-run mdoc the doc writer must have first build the product. That's problematic because that requires the doc writer to maintain a working build environment and depending on the maturity of the build that could be challenging.

On XF our goal is to have the developer run mdoc after building locally with changes that add new public APIs so that xml mdoc stubs are generated and can be included in the PR. The build system then enforces that every PR has xml stubs for all new APIs by running mdoc and failing if the generated xml files don't match those submitted in the PR. After the stubs are checked in then the doc writer can fill in those stubs and submit a PR without having to build.

See also: https://github.com/mono/api-doc-tools/issues/38. Note that for whatever reason we don't see `index.xml` updated for the 813 PR.

**Comment by joelmartinez** [comment] 2017-03-14 21:47
Unfortunately, this request runs at odds with the way several other customers use mdoc ... they do what you describe, or running mdoc _precisely_ in order for mdoc to re-organize whitespace to avoid noisy whitespace check-ins :/

I'm going to apply the wontfix label _for now_, and probably close this later ... but leaving it open for discussion

**Comment by jonpryor** [comment] 2017-03-15 01:06
>  I expect mdoc to preserve that whitespace formatting the next time it's run

What confuses me is that mdoc *does* preserve whitespace, *significant whitespace*. As such, I can line-wrap [my mdoc documentation to ~80 characters](https://github.com/mono/mono/blob/876d186/mcs/class/Mono.Options/Documentation/en/Mono.Options/Option.xml#L11-L16) and have the whitespace preserved during `mdoc update`, because intra-element whitespace is significant.

I thus am at a loss understanding your scenario and what the problem is. The linked Xamarin.Forms PR doesn't help clarify my understanding.

**Closed** 2017-04-03 14:06 UTC
Labels: wontfix
