### ISSUE TITLE
No distinction between versions re. getters and setters

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#410] opened 2019-02-01 19:39 UTC
Example: https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.nettcpbinding.reliablesession?view=netframework-4.7.2

It seems that mdoc is not knowing how to handle the different signatures between versions.
Get and set should exist on the later versions like we used to have on MSDN.

.NET Framework 3.0:
.property instance class System.ServiceModel.OptionalReliableSession
        ReliableSession()
{
  .get instance class System.ServiceModel.OptionalReliableSession System.ServiceModel.NetTcpBinding::get_ReliableSession()
} // end of property NetTcpBinding::ReliableSession

.NET Framework 4.8:
.property instance class System.ServiceModel.OptionalReliableSession
        ReliableSession()
{
  .get instance class System.ServiceModel.OptionalReliableSession System.ServiceModel.NetTcpBinding::get_ReliableSession()
  .set instance void System.ServiceModel.NetTcpBinding::set_ReliableSession(class System.ServiceModel.OptionalReliableSession)
} // end of property NetTcpBinding::ReliableSession

**Comment by joelmartinez** [comment] 2019-02-01 19:55
A few implementation notes for when we work on this:

- Review these attributes, and why the setter doesn't show up for .net 4.8: https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L2713-L2717
- Part of the issue is that we use the `ILAsm` signature as the ultimate signifier of "uniqueness" in mdoc (indeed, even docid gives no indication on whether a property has a getter or setter). So while the C# signature shows the get, the [ILAsm signature](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ServiceModel/NetTcpBinding.xml#L692) doesn't currently show any getters or setters … so we'll have to figure out how to represent the multiline syntax in an XML Attribute.

**Comment by joelmartinez** [comment] 2019-09-03 18:17
This has been resolved with mdoc 5.7.4.10

**Closed by joelmartinez** 2019-09-03 18:17 UTC
Labels: enhancement
